#!/bin/bash
error() {
    echo "`TZ=UTC date`: $0: error: $@" >&2
    exit 1
}

EXE="./bin/exec"
CONFIG_ID="$1"
INSTANCE_ID="$2"
SEED="$3"
INSTANCE="$4"

# Remove os 4 primeiros argumentos (id, instancia_id, seed, nome_instancia)
shift 4 || error "Not enough parameters"

# O que sobra são as flags (--maxEvals 15 --probT 0.8 ...)
CONFIG_PARAMS=$*

STDOUT=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stdout
STDERR=c${CONFIG_ID}-${INSTANCE_ID}-${SEED}.stderr

if [ ! -x "${EXE}" ]; then
    error "${EXE}: not found or not executable (pwd: $(pwd))"
fi

# Executa o C++ com valores fixos + as flags do iRace
$EXE --instancia $INSTANCE --maxEvals 50000 --popSize 100 $CONFIG_PARAMS 1> $STDOUT 2> $STDERR

if [ ! -s "${STDOUT}" ]; then
    error "${STDOUT}: No such file or directory"
fi

# Captura apenas os números
COST=$(cat ${STDOUT} | tr -d ' \n\r')

if ! [[ "$COST" =~ ^[-+0-9.e]+$ ]] ; then
    error "${STDOUT}: Output is not a number. Output was: '$COST'"
fi

echo "$COST"

rm -f "${STDOUT}" "${STDERR}"
rm -f best.* stat.* cmp.*
exit 0